services:
  - type: web
    name: ikigai-website
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true # Cela générera automatiquement une valeur sécurisée 